FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY customer-service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY shared ./shared

COPY customer-service/app ./app

EXPOSE 8001

CMD [
    "uvicorn",
    "app.main:app",
    "--host",
    "0.0.0.0",
    "--port",
    "8001"
]